### ISSUE TITLE
-name- shows name of first person that connected to server, not name of person it refers to

### ISSUE THREAD

**Issue by uszasty** [AlaDyn172/MOTD#2]
In example, in "-name- joined the game" notification. When first player, player1 connects, it shows 'player1 joined the hame', but when another player, player2 connects, it shows again 'player1 joined the game'. It doesn't show any error message in console.

My server is running in offline mode if this is vital info

**Comment by uszasty** [comment]
Also, a suggestion to have option to disable motd messages in this plugin, so default ones are used

**Comment by AlaDyn172** [comment]
Resolved. The new version will be release!
